import { collectMarkdownHeadings } from "@tanstack/markdown/extensions/headings";
import { parseMarkdown } from "@tanstack/markdown/parser";
import { defineConfig } from "tomekit";
import type { Source } from "tomekit";
import { z } from "zod";

import { sections } from "./src/lib/sections";

function withHeadings<TMetadata extends object>({
  body,
  metadata,
}: Source<TMetadata>) {
  const document = parseMarkdown(body, { headingIds: true });

  const headings = collectMarkdownHeadings(document).flatMap(
    ({ id, level, text }) => (level === 2 ? [{ id, text }] : [])
  );

  return { body: document, metadata: { ...metadata, headings } };
}

export default defineConfig({
  collections: {
    docs: {
      directory: "content/docs",
      schema: z.object({
        description: z.string(),
        order: z.number(),
        section: z.enum(sections),
        title: z.string(),
      }),
      transform: withHeadings,
    },
    // Generated by scripts/api-reference.ts: one page per export, linked from the API reference index pages.
    reference: {
      directory: "content/reference",
      schema: z.object({
        kind: z.enum([
          "Class",
          "Function",
          "Interface",
          "Type Alias",
          "Variable",
        ]),
        name: z.string(),
      }),
      transform: withHeadings,
    },
  },
});
