import { PluginError } from "./plugin-error";

/** `tomekit/content` was imported without the `tomekit()` Vite plugin. */
class MissingPluginError extends PluginError {
  override name = "MissingPluginError";

  constructor() {
    super(
      "tomekit/content is generated by the tomekit() Vite plugin. Add it to the plugins in your Vite config."
    );
  }
}

export { MissingPluginError };
