import type { Content } from "./index";

function missingPlugin(): never {
  throw new Error(
    "tomekit/content is generated by the tomekit() Vite plugin. Add it to the plugins in your Vite config."
  );
}

/** Every collection in your config, keyed by name. Provided by the `tomekit()` Vite plugin. */
const content: Content = missingPlugin();

export { content };
