import type { Content } from "./index";

function missingPlugin(): never {
  throw new Error(
    "tomekit/content is generated by the tomekit() Vite plugin. Add it to the plugins in your Vite config."
  );
}

/**
 * Every collection in your config, keyed by name. Provided by the `tomekit()`
 * Vite plugin; importing it without the plugin throws.
 *
 * @example
 * ```ts
 * import { content } from "tomekit/content";
 *
 * content.posts.get("hello-world");
 * ```
 */
const content: Content = missingPlugin();

export { content };
