import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const HEADER =
  "// Generated by tomekit to type `tomekit/content`. Commit it; it only changes if your config file moves.";

/** The declaration that registers the config's type, relative to where it is written. */
function declaration(configPath: string, dtsPath: string) {
  const relative = path
    .relative(path.dirname(dtsPath), configPath)
    .split(path.sep)
    .join("/")
    .replace(/\.[cm]?[jt]s$/u, "");
  const specifier = relative.startsWith(".") ? relative : `./${relative}`;

  return `${HEADER}
import type config from ${JSON.stringify(specifier)};

declare module "tomekit" {
  interface Register {
    config: typeof config;
  }
}
`;
}

/**
 * Writes the declaration if the file is missing or still tomekit's own. A file
 * without the header was edited by hand and is left alone.
 */
async function writeDeclaration(configPath: string, dtsPath: string) {
  const next = declaration(configPath, dtsPath);
  const current = await readFile(dtsPath, "utf-8").catch(() => null);
  if (current === next || (current !== null && !current.startsWith(HEADER))) {
    return false;
  }
  await writeFile(dtsPath, next);
  return true;
}

export { declaration, writeDeclaration };
