// Every error class lives here, so all of tomekit's messages are in one place.
// oxlint-disable max-classes-per-file
import type { Issue } from "./parse";

/** The base of every error tomekit throws. */
class TomekitError extends Error {
  override name = "TomekitError";
}

/** `tomekit.config.ts` could not be used. */
class ConfigError extends TomekitError {
  override name = "ConfigError";
}

class ConfigLoadError extends ConfigError {
  override name = "ConfigLoadError";

  /** `file` is relative to the root; `cause` is what importing it threw. */
  constructor(file: string, cause: unknown) {
    const message = cause instanceof Error ? cause.message : String(cause);
    super(`${file} failed to load: ${message}`, { cause });
  }
}

class MissingDefaultExportError extends ConfigError {
  override name = "MissingDefaultExportError";

  constructor(file: string) {
    super(
      `${file} must export a config as its default export: export default defineConfig({ collections: { ... } })`
    );
  }
}

class InvalidConfigError extends ConfigError {
  override name = "InvalidConfigError";
  readonly issues: readonly string[];

  constructor(file: string, issues: readonly string[]) {
    super([`${file} is invalid:`, ...issues].join("\n"));
    this.issues = issues;
  }
}

/** A problem with one content file, printed as `file:line:column: message`. */
class ContentError extends TomekitError {
  override name = "ContentError";
  readonly column: number | undefined;
  /** Relative to the project root. */
  readonly file: string;
  readonly line: number | undefined;

  constructor(file: string, issue: Issue, options?: ErrorOptions) {
    const location = [file, issue.line, issue.column]
      .filter((part) => part !== undefined)
      .join(":");
    super(`${location}: ${issue.message}`, options);
    this.column = issue.column;
    this.file = file;
    this.line = issue.line;
  }
}

/** Every broken file in a build, one per line. */
class BrokenContentError extends TomekitError {
  override name = "BrokenContentError";
  readonly errors: readonly ContentError[];

  constructor(errors: readonly ContentError[]) {
    const files = new Set(errors.map((error) => error.file)).size;
    const heading = `${files} content ${files === 1 ? "file has" : "files have"} errors:`;
    super([heading, ...errors.map((error) => error.message)].join("\n"));
    this.errors = errors;
  }
}

/** A `transform` returned something tomekit cannot serve. Reported as the cause of the file's `ContentError`. */
class TransformError extends TomekitError {
  override name = "TransformError";
}

class UnserializableValueError extends TransformError {
  override name = "UnserializableValueError";

  /** `what` reads as a noun phrase, eg `a function`; `at` is the key path, or `""` for the root. */
  constructor(what: string, at: string) {
    const where = at === "" ? "" : ` at ${at}`;
    super(
      `cannot write ${what}${where} into content. Return plain data, strings, numbers, Dates, Maps, Sets, URLs or RegExps from transform.`
    );
  }
}

class SlugChangedError extends TransformError {
  override name = "SlugChangedError";

  constructor(slug: string, changedTo: unknown) {
    super(
      `transform changed slug "${slug}" to ${JSON.stringify(changedTo)}. Set \`slug\` in the frontmatter instead, so lookups and types agree.`
    );
  }
}

/** `tomekit/content` was used in a way the Vite plugin cannot serve. */
class PluginError extends TomekitError {
  override name = "PluginError";
}

class MissingPluginError extends PluginError {
  override name = "MissingPluginError";

  constructor() {
    super(
      "tomekit/content is generated by the tomekit() Vite plugin. Add it to the plugins in your Vite config."
    );
  }
}

class UnknownCollectionError extends PluginError {
  override name = "UnknownCollectionError";

  constructor(moduleId: string, known: readonly string[]) {
    const names = known.map((name) => JSON.stringify(name)).join(", ");
    super(
      `${moduleId} does not exist. Collections in the config: ${names || "none"}.`
    );
  }
}

class PluginNotReadyError extends PluginError {
  override name = "PluginNotReadyError";

  constructor() {
    super("the plugin was used before Vite resolved its config");
  }
}

export {
  BrokenContentError,
  ConfigError,
  ConfigLoadError,
  ContentError,
  InvalidConfigError,
  MissingDefaultExportError,
  MissingPluginError,
  PluginError,
  PluginNotReadyError,
  SlugChangedError,
  TomekitError,
  TransformError,
  UnknownCollectionError,
  UnserializableValueError,
};
