import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const HEADER = "// Generated by tomekit. Do not edit.";

interface GeneratedCollection {
  name: string;
  slugs: readonly string[];
}

/** `blog_posts` → `BlogPosts`, so the collection key can name a type. */
function typeName(name: string): string {
  return name
    .split("_")
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join("");
}

function importPath(from: string, to: string): string {
  const relative = path
    .relative(from, to)
    .split(path.sep)
    .join("/")
    .replace(/\.[cm]?[jt]s$/u, "");

  return relative.startsWith(".") ? relative : `./${relative}`;
}

function collectionFile(
  { name, slugs }: GeneratedCollection,
  configImport: string
): string {
  const type = typeName(name);

  const slugType =
    slugs.length === 0
      ? "never"
      : slugs.map((slug) => JSON.stringify(slug)).join(" | ");

  return `${HEADER}
import type { Collection as _Collection, InferDocument as _InferDocument, WithSlug as _WithSlug } from "tomekit";
import type config from ${JSON.stringify(configImport)};

/** Every slug in the \`${name}\` collection. */
export type ${type}Slug = ${slugType};

/** A document in the \`${name}\` collection. */
export type ${type} = _WithSlug<_InferDocument<(typeof config)["collections"][${JSON.stringify(name)}]>, ${type}Slug>;

/** The \`${name}\` collection. */
declare const collection: _Collection<${type}, ${type}Slug>;
export default collection;
`;
}

function indexFile(collections: readonly GeneratedCollection[]): string {
  const types = collections.map(({ name }) => typeName(name));

  const reexports = collections
    .map(({ name }, index) => {
      const type = types[index];

      return `export type { ${type}, ${type}Slug } from ${JSON.stringify(`./content/${name}`)};`;
    })
    .join("\n");

  const entries = collections
    .map(
      ({ name }) =>
        `  /** The \`${name}\` collection. */
  ${JSON.stringify(name)}: typeof import(${JSON.stringify(`./content/${name}`)}).default;`
    )
    .join("\n");

  const union = types.length === 0 ? "never" : types.join(" | ");

  const names =
    collections.length === 0
      ? "never"
      : collections.map(({ name }) => JSON.stringify(name)).join(" | ");

  return `${HEADER}
${reexports}

/** A document from any collection. */
export type AnyDocument = ${union};

/** The name of any collection, eg to check a route param before \`content[name]\`. */
export type CollectionName = ${names};

/** Every collection in your config, keyed by name. */
export declare const content: {
${entries}
};
`;
}

/**
 * Writes the types for `tomekit/content` to `<directory>/content.d.ts` and
 * `<directory>/content/<name>.d.ts`, touching only files whose contents changed so TypeScript does not reload for nothing.
 * Returns whether anything was written or removed.
 */
async function writeTypes(
  directory: string,
  configPath: string,
  collections: readonly GeneratedCollection[]
): Promise<boolean> {
  const contentDirectory = path.join(directory, "content");
  await mkdir(contentDirectory, { recursive: true });
  const configImport = importPath(contentDirectory, configPath);

  // Beside the folder rather than as its index.d.ts, so a collection can be named `index`.
  const files = new Map<string, string>([
    [path.join(directory, "content.d.ts"), indexFile(collections)],
    ...collections.map(
      (collection) =>
        [
          path.join(contentDirectory, `${collection.name}.d.ts`),
          collectionFile(collection, configImport),
        ] as const
    ),
  ]);

  const existing = await readdir(contentDirectory);

  const stale = existing
    .map((file) => path.join(contentDirectory, file))
    .filter((file) => !files.has(file));

  const removed = await Promise.all(
    stale.map(async (file) => {
      await rm(file, { force: true });

      return true;
    })
  );

  const written = await Promise.all(
    [...files].map(async ([file, source]) => {
      const current = await readFile(file, "utf-8").catch(() => null);

      if (current === source) {
        return false;
      }

      await writeFile(file, source);

      return true;
    })
  );

  const changed = [...removed, ...written].includes(true);

  return changed;
}

export { type GeneratedCollection, typeName, writeTypes };
