import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const HEADER = "// Generated by tomekit. Do not edit.";

interface GeneratedCollection {
  name: string;
  slugs: readonly string[];
}

/** `blog-posts` → `BlogPosts`, so the collection key can name a type. */
function typeName(name: string): string {
  const pascal = name
    .split(/[^\dA-Za-z]+/u)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join("");
  return /^\d/u.test(pascal) ? `_${pascal}` : pascal;
}

function importPath(from: string, to: string): string {
  const relative = path
    .relative(from, to)
    .split(path.sep)
    .join("/")
    .replace(/\.[cm]?[jt]s$/u, "");
  return relative.startsWith(".") ? relative : `./${relative}`;
}

function collectionFile(
  { name, slugs }: GeneratedCollection,
  configImport: string
): string {
  const type = typeName(name);
  const slugType =
    slugs.length === 0
      ? "never"
      : slugs.map((slug) => JSON.stringify(slug)).join(" | ");
  return `${HEADER}
import type { InferDocument } from "tomekit";
import type config from ${JSON.stringify(configImport)};

export type ${type} = InferDocument<(typeof config)["collections"][${JSON.stringify(name)}]>;

export type ${type}Slug = ${slugType};
`;
}

function indexFile(collections: readonly GeneratedCollection[]): string {
  const imports = collections
    .map(({ name }) => {
      const type = typeName(name);
      return `import type { ${type}, ${type}Slug } from ${JSON.stringify(`./${name}`)};`;
    })
    .join("\n");
  const entries = collections
    .map(({ name }) => {
      const type = typeName(name);
      return `  ${JSON.stringify(name)}: CollectionQuery<${type}, ${type}Slug>;`;
    })
    .join("\n");
  const reexports = collections
    .map(({ name }) => {
      const type = typeName(name);
      return `export type { ${type}, ${type}Slug } from ${JSON.stringify(`./${name}`)};`;
    })
    .join("\n");

  return `${HEADER}
import type { CollectionQuery } from "tomekit";
${imports}

export declare const content: {
${entries}
};

${reexports}
`;
}

/**
 * Writes the types for `tomekit/content` into `<directory>/content`, touching
 * only files whose contents changed so TypeScript does not reload for nothing.
 * Returns whether anything was written or removed.
 */
async function writeTypes(
  directory: string,
  configPath: string,
  collections: readonly GeneratedCollection[]
): Promise<boolean> {
  const contentDirectory = path.join(directory, "content");
  await mkdir(contentDirectory, { recursive: true });
  const configImport = importPath(contentDirectory, configPath);

  const files = new Map<string, string>([
    ["index.d.ts", indexFile(collections)],
    ...collections.map(
      (collection) =>
        [
          `${collection.name}.d.ts`,
          collectionFile(collection, configImport),
        ] as const
    ),
  ]);

  const existing = await readdir(contentDirectory);
  const stale = existing.filter((file) => !files.has(file));
  const removed = await Promise.all(
    stale.map(async (file) => {
      await rm(path.join(contentDirectory, file), { force: true });
      return true;
    })
  );
  const written = await Promise.all(
    [...files].map(async ([file, source]) => {
      const target = path.join(contentDirectory, file);
      const current = await readFile(target, "utf-8").catch(() => null);
      if (current === source) {
        return false;
      }
      await writeFile(target, source);
      return true;
    })
  );
  const changed = [...removed, ...written].includes(true);
  return changed;
}

export { type GeneratedCollection, typeName, writeTypes };
